### ISSUE TITLE
Initialize backend frameworks, libraries, and tools.

### ISSUE THREAD

**Issue by tr4ce123** [tr4ce123/app-team-takehome#1]
# TODO:
## Frameworks / Tools
- [x] Install FastAPI, SQLAlchemy, Uvicorn, Pytest, and Pydantic into backend virtual env.
- [x] Use a SQLite database that comes with FastAPI from its documentation
- [x] Create Postman workspace for testing.

## General setup
- [x] Setup models, services, tests, and api folders.
- [x] Create dummy data in the form of Pydantic models and simple API call.
