### ISSUE TITLE
Implement workout data aggregation for users

### ISSUE THREAD

**Issue by tr4ce123** [tr4ce123/app-team-takehome#2]
# TODO:
## Users
- [ ] Create Users model and entity 
- [ ] Write basic CRUD API's
- [ ] Create a one-to-many relationship between users and workouts

## Data aggregation
- [x] Write helper functions to parse the created_at times for each workout to see what month it was in. Maybe allow the user to set their own date in a specific format? This would allow them to go back to create their own date for the workout and not restrict them to the current day.
- [x] Either way above note works out, write a function(s) that uses the datetime to gather the average duration, average distance, total duration, and total distance.
