### ISSUE TITLE
Implement OpenAI API and Weather API

### ISSUE THREAD

**Issue by tr4ce123** [tr4ce123/app-team-takehome#3]
# TODO:
## API's role 
- [x] Can use ChatGPT and Weather API in combination to suggest what to wear for a workout.
- [x] Can use ChatGPT for simple guidance on workouts and how to improve etc.
- [x] Create a few basic weather API calls so the user can know what to wear on their run

## Logistics
- [x] Either way it will get its own service
- [ ] Create a new table for ChatGPT responses and queries and write different functions for a specific type of prompt to give to ChatGPT
